vrrp_script checkapi {
  script "/etc/keepalived/checkapi.sh"
  interval 2 # Uruchamiaj skrypt co 2 sekundy
  timeout 5 # Poczekaj do 5 sekund na skrypt przed przyjęciem niezerowego kodu wyjścia
  fall 3 # Jeśli skrypt zwraca kod niezerowy 3 razy z rzędu, wprowadź stan FAULT
  rise 3 # Jeśli skrypt zwraca kod zero 3 razy z rzędu, wyjdź ze stanu FAULT
  weight -10 # Zmniejsz priorytet o 10 przy wykrytej awarii
}

vrrp_instance VI_1 {
    state ACTIVE
    interface enp0s3
    virtual_router_id 1
    priority 100
    advert_int 2
    authentication {
        auth_type PASS
        auth_pass mojehaslo
    }
    virtual_ipaddress {
        192.168.101.111
    }
    track_script {
        checkapi
    }
}
