apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
data:
  # key: value
  # file: |
  #   content
  # ---
  nginx.conf: |
    user nginx;
    worker_processes 1;
    events {
      worker_connections  1024;
    }
    http {
      server {
        listen 80;
        server_name example.com;
        location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm index.php;
        }
        location /test {
          return 401;
        }
      }
    }