apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: nginx-redirectssl
spec:
  redirectScheme:
    scheme: https 
    permanent: true
    port: "443"


---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-http
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`nginx.adminakademia.pl`)
      kind: Rule
      middlewares:
        - name: nginx-redirectssl
      services:
        - name: nginx-deploy-czerwony
          port: 80


---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-https
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nginx.adminakademia.pl`)
      kind: Rule
      services:
        - name: nginx-deploy-czerwony
          port: 80
  tls:
    certResolver: letsencrypt

